export const GET_ITEMS = "GET_ITEMS";
export const CREATE_ITEM = "CREATE_ITEM";
export const ADD_LIKE = "ADD_LIKE";
export const LIKE_PERSISTENCE_SUCCESS = "LIKE_PERSISTENCE_SUCCESS";
export const LIKE_PERSISTENCE_FAILED = "LIKE_PERSISTENCE_FAILED"; 
